name: CI & Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ci-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pytest
        run: |
          pytest -q

  build-and-push:
    name: Build, push image and deploy to Render
    runs-on: ubuntu-latest
    needs: test
    env:
      IMAGE: ${{ secrets.REGISTRY }}/lunessasignels:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          file: ./Dockerfile

      - name: Trigger Render deploy with retries
        if: ${{ secrets.RENDER_API_KEY != '' && secrets.RENDER_SERVICE_ID != '' }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          set -euo pipefail

          echo "Triggering Render deploy for service $RENDER_SERVICE_ID with retries"
          MAX_ATTEMPTS=3
          SLEEP_BASE=5

          for attempt in $(seq 1 $MAX_ATTEMPTS); do
            echo "▶ Deploy attempt #${attempt}"
            if curl --fail -s -X POST \
                 -H "Content-Type: application/json" \
                 -H "Authorization: Bearer $RENDER_API_KEY" \
                 -d "{\"serviceId\":\"$RENDER_SERVICE_ID\"}" \
                 https://api.render.com/deploys | jq -r .message; then
              echo "✅ Deploy succeeded on attempt ${attempt}"
              break
            else
              echo "❗ Deploy failed on attempt ${attempt}"
              if [ "$attempt" -lt "$MAX_ATTEMPTS" ]; then
                sleep $(( SLEEP_BASE ** attempt ))
                echo "⏳ Retrying..."
              else
                echo "🚨 All ${MAX_ATTEMPTS} deploy attempts failed."
                exit 1
              fi
            fi
          done

# Required repository secrets:
# - REGISTRY: e.g. ghcr.io/your-org
# - REGISTRY_USERNAME: registry username (for GHCR use GITHUB_ACTOR)
# - REGISTRY_TOKEN: registry token (for GHCR use GITHUB_TOKEN or personal access token with packages:write)
# - RENDER_API_KEY: (optional) Render API key to trigger deploys
# - RENDER_SERVICE_ID: (optional) Render service ID to deploy
